#!/usr/bin/zsh

MENU_INSTALL_SELECTION_TEMP_FILE=$(tempfile 2>/dev/null) || MENU_INSTALL_SELECTION_TEMP_FILE=/tmp/install-tmp
MENU_ACTION_SELECTION_TEMP_FILE=$(tempfile 2>/dev/null) || MENU_ACTION_SELECTION_TEMP_FILE=/tmp/action-tmp
INSTALL_TEMP_FILE=$(tempfile 2>/dev/null) || INSTALL_TEMP_FILE=/tmp/superconsole-setup-tmp

dialog --clear --no-tags --checklist "Install Software Packages:" 20 100 1 \
        'gcc' 'Install GCC C++ Compiler' off \
        'clang' 'Install Clang C++ Compiler' off \
        'make' 'Install make' off \
        'cmake' 'Install CMake' off \
        'python2' 'Install Python 2' off \
        'qt5' 'Install Qt5' off \
        'qt5-debug' 'Install Qt5 (Debug)' off \
        'qtcreator' 'Install QtCreator' off \
        'qtcreator-doc' 'Install additional QtCreator Help for C++ and CMake' off \
        'doxygen' 'Install Doxygen' off \
        2>$MENU_INSTALL_SELECTION_TEMP_FILE
clear

dialog --clear --no-tags --checklist "Choose Actions:" 20 100 1 \
	    'update' 'Update installed software' off \
        'qtcreator-customize' 'Customize QtCreator for more convenient use.' off \
        'clean-cache' 'Clean installed package cache to save storage space' off \
        2>$MENU_ACTION_SELECTION_TEMP_FILE
clear

for value in `cat $MENU_INSTALL_SELECTION_TEMP_FILE`
do
    source "/3rdparty/install-scripts/$value" $INSTALL_TEMP_FILE
done

pacman --noconfirm --needed -S `cat $INSTALL_TEMP_FILE`

for value in `cat $MENU_ACTION_SELECTION_TEMP_FILE`
do
    source "/3rdparty/configure-scripts/$value"
done

rm $INSTALL_TEMP_FILE 2>/dev/null
unset INSTALL_TEMP_FILE 2>/dev/null

rm $MENU_ACTION_SELECTION_TEMP_FILE 2>/dev/null
unset MENU_ACTION_SELECTION_TEMP_FILE 2>/dev/null

rm $MENU_ACTION_SELECTION_TEMP_FILE 2>/dev/null
unset MENU_ACTION_SELECTION_TEMP_FILE 2>/dev/null